[versions]
kotlin = "1.9.10"
gradle = "8.1.2"
gradle-plugin = "8.2.0"
hawk = "2.0.1"
joda-time = "2.12.2"
compiler-extension = "1.5.3"

junit = "4.13.2"
junit-ext = "1.1.5"

logger = "2.2.0"
mockinizer = "1.6.0"
mockk = "1.13.4"
mockwebserver = "4.10.0"
multidex = "2.0.1"

room = "2.6.0"
gson = "2.10.1"
retrofit = "2.9.0"
okhttp = "4.10.0"
core-ktx = "1.12.0"
material = "1.10.0"
lifecycle = "2.6.2"
appcompat = "1.6.1"

startup-runtime = "1.1.1"
swiperefreshlayout = "1.1.0"
test-runner = "1.5.2"
espresso-core = "3.5.1"

constraintlayout = "2.1.4"
paging-runtime = "3.2.1"
easyimage = "3.2.0"
customactivityoncrash = "2.4.0"
navigation = "2.7.4"
glide = "4.15.1"
material-dialogs = "3.3.0"
zelory-compressor = "3.0.1"

activity-compose = "1.8.0"
compose-bom = "2023.03.00"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hawk = { module = "com.orhanobut:hawk", version.ref = "hawk" }
joda-time = { module = "joda-time:joda-time", version.ref = "joda-time" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }

logger = { module = "com.orhanobut:logger", version.ref = "logger" }
mockinizer = { module = "com.github.donfuxx:Mockinizer", version.ref = "mockinizer" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

core-ktx = { group = "androidx.core", name="core-ktx", version.ref = "core-ktx" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }

material = { module = "com.google.android.material:material", version.ref = "material" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "material-dialogs" }
material-dialogs-datetime = { module = "com.afollestad.material-dialogs:datetime", version.ref = "material-dialogs" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-runtime" }
easyimage = { module = "com.github.jkwiecien:EasyImage", version.ref = "easyimage" }
customactivityoncrash = { module = "cat.ereza:customactivityoncrash", version.ref = "customactivityoncrash" }
zelory-compressor = { module = "id.zelory:compressor", version.ref = "zelory-compressor" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[bundles]